---
abstract: 'Str type parameterizable by length.'
author:
  - 'Chris Andrews <chris@nodnol.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::NoTabs: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.93'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Types-Varchar
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
  MooseX::Types: 0
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
